#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:2.0.50727.1433
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Angel_to_003.DataSourceModule.Interface.Schema
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[System.Data.Linq.Mapping.DatabaseAttribute(Name="ANGEL_TO_001_TEST4")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCCAR_CONDITION(CCAR_CONDITION instance);
    partial void UpdateCCAR_CONDITION(CCAR_CONDITION instance);
    partial void DeleteCCAR_CONDITION(CCAR_CONDITION instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::Angel_to_003.DataSourceModule.Interface.Properties.Settings.Default.ANGEL_TO_001_TEST4ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CCAR_CONDITION> CCAR_CONDITION
		{
			get
			{
				return this.GetTable<CCAR_CONDITION>();
			}
		}
		
		[Function(Name="dbo.uspVCAR_CONDITION_SelectCar")]
		public ISingleResult<uspVCAR_CONDITION_SelectCarResult> uspVCAR_CONDITION_SelectCar([Parameter(DbType="DateTime")] System.Nullable<System.DateTime> p_start_date, [Parameter(DbType="DateTime")] System.Nullable<System.DateTime> p_end_date, [Parameter(DbType="VarChar(100)")] string p_Str, [Parameter(DbType="TinyInt")] System.Nullable<byte> p_Srch_Type, [Parameter(DbType="SmallInt")] System.Nullable<short> p_Top_n_by_rank)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_start_date, p_end_date, p_Str, p_Srch_Type, p_Top_n_by_rank);
			return ((ISingleResult<uspVCAR_CONDITION_SelectCarResult>)(result.ReturnValue));
		}
		
		[Function(Name="dbo.uspVCAR_CONDITION_SelectFreight")]
		public ISingleResult<uspVCAR_CONDITION_SelectFreightResult> uspVCAR_CONDITION_SelectFreight([Parameter(DbType="DateTime")] System.Nullable<System.DateTime> p_start_date, [Parameter(DbType="DateTime")] System.Nullable<System.DateTime> p_end_date, [Parameter(DbType="VarChar(100)")] string p_Str, [Parameter(DbType="TinyInt")] System.Nullable<byte> p_Srch_Type, [Parameter(DbType="SmallInt")] System.Nullable<short> p_Top_n_by_rank)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), p_start_date, p_end_date, p_Str, p_Srch_Type, p_Top_n_by_rank);
			return ((ISingleResult<uspVCAR_CONDITION_SelectFreightResult>)(result.ReturnValue));
		}
	}
	
	[Table(Name="dbo.CCAR_CONDITION")]
	public partial class CCAR_CONDITION : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private byte _sys_status;
		
		private string _sys_comment;
		
		private System.DateTime _sys_date_modified;
		
		private System.DateTime _sys_date_created;
		
		private string _sys_user_modified;
		
		private string _sys_user_created;
		
		private decimal _car_id;
		
		private System.Nullable<decimal> _ts_type_master_id;
		
		private System.Nullable<decimal> _employee_id;
		
		private decimal _run;
		
		private decimal _speedometer_start_indctn;
		
		private decimal _speedometer_end_indctn;
		
		private decimal _id;
		
		private decimal _last_run;
		
		private System.Nullable<decimal> _last_ts_type_master_id;
		
		private decimal _fuel_start_left;
		
		private decimal _fuel_end_left;
		
		private System.Nullable<decimal> _overrun;
		
		private bool _in_tolerance;
		
		private System.Nullable<decimal> _ts_type_route_detail_id;
		
		private System.Nullable<decimal> _last_ts_type_route_detail_id;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void Onsys_statusChanging(byte value);
    partial void Onsys_statusChanged();
    partial void Onsys_commentChanging(string value);
    partial void Onsys_commentChanged();
    partial void Onsys_date_modifiedChanging(System.DateTime value);
    partial void Onsys_date_modifiedChanged();
    partial void Onsys_date_createdChanging(System.DateTime value);
    partial void Onsys_date_createdChanged();
    partial void Onsys_user_modifiedChanging(string value);
    partial void Onsys_user_modifiedChanged();
    partial void Onsys_user_createdChanging(string value);
    partial void Onsys_user_createdChanged();
    partial void Oncar_idChanging(decimal value);
    partial void Oncar_idChanged();
    partial void Onts_type_master_idChanging(System.Nullable<decimal> value);
    partial void Onts_type_master_idChanged();
    partial void Onemployee_idChanging(System.Nullable<decimal> value);
    partial void Onemployee_idChanged();
    partial void OnrunChanging(decimal value);
    partial void OnrunChanged();
    partial void Onspeedometer_start_indctnChanging(decimal value);
    partial void Onspeedometer_start_indctnChanged();
    partial void Onspeedometer_end_indctnChanging(decimal value);
    partial void Onspeedometer_end_indctnChanged();
    partial void OnidChanging(decimal value);
    partial void OnidChanged();
    partial void Onlast_runChanging(decimal value);
    partial void Onlast_runChanged();
    partial void Onlast_ts_type_master_idChanging(System.Nullable<decimal> value);
    partial void Onlast_ts_type_master_idChanged();
    partial void Onfuel_start_leftChanging(decimal value);
    partial void Onfuel_start_leftChanged();
    partial void Onfuel_end_leftChanging(decimal value);
    partial void Onfuel_end_leftChanged();
    partial void OnoverrunChanging(System.Nullable<decimal> value);
    partial void OnoverrunChanged();
    partial void Onin_toleranceChanging(bool value);
    partial void Onin_toleranceChanged();
    partial void Onts_type_route_detail_idChanging(System.Nullable<decimal> value);
    partial void Onts_type_route_detail_idChanged();
    partial void Onlast_ts_type_route_detail_idChanging(System.Nullable<decimal> value);
    partial void Onlast_ts_type_route_detail_idChanged();
    #endregion
		
		public CCAR_CONDITION()
		{
			OnCreated();
		}
		
		[Column(Storage="_sys_status", DbType="TinyInt NOT NULL")]
		public byte sys_status
		{
			get
			{
				return this._sys_status;
			}
			set
			{
				if ((this._sys_status != value))
				{
					this.Onsys_statusChanging(value);
					this.SendPropertyChanging();
					this._sys_status = value;
					this.SendPropertyChanged("sys_status");
					this.Onsys_statusChanged();
				}
			}
		}
		
		[Column(Storage="_sys_comment", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string sys_comment
		{
			get
			{
				return this._sys_comment;
			}
			set
			{
				if ((this._sys_comment != value))
				{
					this.Onsys_commentChanging(value);
					this.SendPropertyChanging();
					this._sys_comment = value;
					this.SendPropertyChanged("sys_comment");
					this.Onsys_commentChanged();
				}
			}
		}
		
		[Column(Storage="_sys_date_modified", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_modified
		{
			get
			{
				return this._sys_date_modified;
			}
			set
			{
				if ((this._sys_date_modified != value))
				{
					this.Onsys_date_modifiedChanging(value);
					this.SendPropertyChanging();
					this._sys_date_modified = value;
					this.SendPropertyChanged("sys_date_modified");
					this.Onsys_date_modifiedChanged();
				}
			}
		}
		
		[Column(Storage="_sys_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_created
		{
			get
			{
				return this._sys_date_created;
			}
			set
			{
				if ((this._sys_date_created != value))
				{
					this.Onsys_date_createdChanging(value);
					this.SendPropertyChanging();
					this._sys_date_created = value;
					this.SendPropertyChanged("sys_date_created");
					this.Onsys_date_createdChanged();
				}
			}
		}
		
		[Column(Storage="_sys_user_modified", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_modified
		{
			get
			{
				return this._sys_user_modified;
			}
			set
			{
				if ((this._sys_user_modified != value))
				{
					this.Onsys_user_modifiedChanging(value);
					this.SendPropertyChanging();
					this._sys_user_modified = value;
					this.SendPropertyChanged("sys_user_modified");
					this.Onsys_user_modifiedChanged();
				}
			}
		}
		
		[Column(Storage="_sys_user_created", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_created
		{
			get
			{
				return this._sys_user_created;
			}
			set
			{
				if ((this._sys_user_created != value))
				{
					this.Onsys_user_createdChanging(value);
					this.SendPropertyChanging();
					this._sys_user_created = value;
					this.SendPropertyChanged("sys_user_created");
					this.Onsys_user_createdChanged();
				}
			}
		}
		
		[Column(Storage="_car_id", DbType="Decimal(38,0) NOT NULL")]
		public decimal car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this.Oncar_idChanging(value);
					this.SendPropertyChanging();
					this._car_id = value;
					this.SendPropertyChanged("car_id");
					this.Oncar_idChanged();
				}
			}
		}
		
		[Column(Storage="_ts_type_master_id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> ts_type_master_id
		{
			get
			{
				return this._ts_type_master_id;
			}
			set
			{
				if ((this._ts_type_master_id != value))
				{
					this.Onts_type_master_idChanging(value);
					this.SendPropertyChanging();
					this._ts_type_master_id = value;
					this.SendPropertyChanged("ts_type_master_id");
					this.Onts_type_master_idChanged();
				}
			}
		}
		
		[Column(Storage="_employee_id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this.Onemployee_idChanging(value);
					this.SendPropertyChanging();
					this._employee_id = value;
					this.SendPropertyChanged("employee_id");
					this.Onemployee_idChanged();
				}
			}
		}
		
		[Column(Storage="_run", DbType="Decimal(18,9) NOT NULL")]
		public decimal run
		{
			get
			{
				return this._run;
			}
			set
			{
				if ((this._run != value))
				{
					this.OnrunChanging(value);
					this.SendPropertyChanging();
					this._run = value;
					this.SendPropertyChanged("run");
					this.OnrunChanged();
				}
			}
		}
		
		[Column(Storage="_speedometer_start_indctn", DbType="Decimal(18,9) NOT NULL")]
		public decimal speedometer_start_indctn
		{
			get
			{
				return this._speedometer_start_indctn;
			}
			set
			{
				if ((this._speedometer_start_indctn != value))
				{
					this.Onspeedometer_start_indctnChanging(value);
					this.SendPropertyChanging();
					this._speedometer_start_indctn = value;
					this.SendPropertyChanged("speedometer_start_indctn");
					this.Onspeedometer_start_indctnChanged();
				}
			}
		}
		
		[Column(Storage="_speedometer_end_indctn", DbType="Decimal(18,9) NOT NULL")]
		public decimal speedometer_end_indctn
		{
			get
			{
				return this._speedometer_end_indctn;
			}
			set
			{
				if ((this._speedometer_end_indctn != value))
				{
					this.Onspeedometer_end_indctnChanging(value);
					this.SendPropertyChanging();
					this._speedometer_end_indctn = value;
					this.SendPropertyChanged("speedometer_end_indctn");
					this.Onspeedometer_end_indctnChanged();
				}
			}
		}
		
		[Column(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Decimal(38,0) NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[Column(Storage="_last_run", DbType="Decimal(18,9) NOT NULL")]
		public decimal last_run
		{
			get
			{
				return this._last_run;
			}
			set
			{
				if ((this._last_run != value))
				{
					this.Onlast_runChanging(value);
					this.SendPropertyChanging();
					this._last_run = value;
					this.SendPropertyChanged("last_run");
					this.Onlast_runChanged();
				}
			}
		}
		
		[Column(Storage="_last_ts_type_master_id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> last_ts_type_master_id
		{
			get
			{
				return this._last_ts_type_master_id;
			}
			set
			{
				if ((this._last_ts_type_master_id != value))
				{
					this.Onlast_ts_type_master_idChanging(value);
					this.SendPropertyChanging();
					this._last_ts_type_master_id = value;
					this.SendPropertyChanged("last_ts_type_master_id");
					this.Onlast_ts_type_master_idChanged();
				}
			}
		}
		
		[Column(Storage="_fuel_start_left", DbType="Decimal(18,9) NOT NULL")]
		public decimal fuel_start_left
		{
			get
			{
				return this._fuel_start_left;
			}
			set
			{
				if ((this._fuel_start_left != value))
				{
					this.Onfuel_start_leftChanging(value);
					this.SendPropertyChanging();
					this._fuel_start_left = value;
					this.SendPropertyChanged("fuel_start_left");
					this.Onfuel_start_leftChanged();
				}
			}
		}
		
		[Column(Storage="_fuel_end_left", DbType="Decimal(18,9) NOT NULL")]
		public decimal fuel_end_left
		{
			get
			{
				return this._fuel_end_left;
			}
			set
			{
				if ((this._fuel_end_left != value))
				{
					this.Onfuel_end_leftChanging(value);
					this.SendPropertyChanging();
					this._fuel_end_left = value;
					this.SendPropertyChanged("fuel_end_left");
					this.Onfuel_end_leftChanged();
				}
			}
		}
		
		[Column(Storage="_overrun", DbType="Decimal(18,9)")]
		public System.Nullable<decimal> overrun
		{
			get
			{
				return this._overrun;
			}
			set
			{
				if ((this._overrun != value))
				{
					this.OnoverrunChanging(value);
					this.SendPropertyChanging();
					this._overrun = value;
					this.SendPropertyChanged("overrun");
					this.OnoverrunChanged();
				}
			}
		}
		
		[Column(Storage="_in_tolerance", DbType="Bit NOT NULL")]
		public bool in_tolerance
		{
			get
			{
				return this._in_tolerance;
			}
			set
			{
				if ((this._in_tolerance != value))
				{
					this.Onin_toleranceChanging(value);
					this.SendPropertyChanging();
					this._in_tolerance = value;
					this.SendPropertyChanged("in_tolerance");
					this.Onin_toleranceChanged();
				}
			}
		}
		
		[Column(Storage="_ts_type_route_detail_id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> ts_type_route_detail_id
		{
			get
			{
				return this._ts_type_route_detail_id;
			}
			set
			{
				if ((this._ts_type_route_detail_id != value))
				{
					this.Onts_type_route_detail_idChanging(value);
					this.SendPropertyChanging();
					this._ts_type_route_detail_id = value;
					this.SendPropertyChanged("ts_type_route_detail_id");
					this.Onts_type_route_detail_idChanged();
				}
			}
		}
		
		[Column(Storage="_last_ts_type_route_detail_id", DbType="Decimal(38,0)")]
		public System.Nullable<decimal> last_ts_type_route_detail_id
		{
			get
			{
				return this._last_ts_type_route_detail_id;
			}
			set
			{
				if ((this._last_ts_type_route_detail_id != value))
				{
					this.Onlast_ts_type_route_detail_idChanging(value);
					this.SendPropertyChanging();
					this._last_ts_type_route_detail_id = value;
					this.SendPropertyChanged("last_ts_type_route_detail_id");
					this.Onlast_ts_type_route_detail_idChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	public partial class uspVCAR_CONDITION_SelectCarResult
	{
		
		private decimal _id;
		
		private byte _sys_status;
		
		private string _sys_comment;
		
		private System.DateTime _sys_date_modified;
		
		private System.DateTime _sys_date_created;
		
		private string _sys_user_modified;
		
		private string _sys_user_created;
		
		private decimal _car_id;
		
		private string _state_number;
		
		private System.Nullable<decimal> _ts_type_master_id;
		
		private string _ts_type_name;
		
		private string _car_mark_model_name;
		
		private decimal _car_mark_id;
		
		private decimal _car_model_id;
		
		private System.Nullable<decimal> _employee_id;
		
		private string _FIO;
		
		private System.Nullable<decimal> _car_state_id;
		
		private string _car_state_name;
		
		private decimal _car_type_id;
		
		private System.Nullable<decimal> _run;
		
		private System.Nullable<decimal> _last_ts_type_master_id;
		
		private char _edit_state;
		
		private System.Nullable<decimal> _fuel_start_left;
		
		private System.Nullable<decimal> _fuel_end_left;
		
		private System.Nullable<decimal> _speedometer_start_indctn;
		
		private System.Nullable<decimal> _speedometer_end_indctn;
		
		private char _sent_to;
		
		private System.Nullable<decimal> _last_run;
		
		private System.Nullable<decimal> _overrun;
		
		private int _in_tolerance;
		
		private System.Nullable<decimal> _ts_type_route_detail_id;
		
		private System.Nullable<decimal> _last_ts_type_route_detail_id;
		
		private System.Nullable<int> _addtnl_ts;
		
		public uspVCAR_CONDITION_SelectCarResult()
		{
		}
		
		[Column(Storage="_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_sys_status", DbType="TinyInt NOT NULL")]
		public byte sys_status
		{
			get
			{
				return this._sys_status;
			}
			set
			{
				if ((this._sys_status != value))
				{
					this._sys_status = value;
				}
			}
		}
		
		[Column(Storage="_sys_comment", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string sys_comment
		{
			get
			{
				return this._sys_comment;
			}
			set
			{
				if ((this._sys_comment != value))
				{
					this._sys_comment = value;
				}
			}
		}
		
		[Column(Storage="_sys_date_modified", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_modified
		{
			get
			{
				return this._sys_date_modified;
			}
			set
			{
				if ((this._sys_date_modified != value))
				{
					this._sys_date_modified = value;
				}
			}
		}
		
		[Column(Storage="_sys_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_created
		{
			get
			{
				return this._sys_date_created;
			}
			set
			{
				if ((this._sys_date_created != value))
				{
					this._sys_date_created = value;
				}
			}
		}
		
		[Column(Storage="_sys_user_modified", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_modified
		{
			get
			{
				return this._sys_user_modified;
			}
			set
			{
				if ((this._sys_user_modified != value))
				{
					this._sys_user_modified = value;
				}
			}
		}
		
		[Column(Storage="_sys_user_created", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_created
		{
			get
			{
				return this._sys_user_created;
			}
			set
			{
				if ((this._sys_user_created != value))
				{
					this._sys_user_created = value;
				}
			}
		}
		
		[Column(Storage="_car_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this._car_id = value;
				}
			}
		}
		
		[Column(Storage="_state_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string state_number
		{
			get
			{
				return this._state_number;
			}
			set
			{
				if ((this._state_number != value))
				{
					this._state_number = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_master_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ts_type_master_id
		{
			get
			{
				return this._ts_type_master_id;
			}
			set
			{
				if ((this._ts_type_master_id != value))
				{
					this._ts_type_master_id = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_name", DbType="VarChar(53)")]
		public string ts_type_name
		{
			get
			{
				return this._ts_type_name;
			}
			set
			{
				if ((this._ts_type_name != value))
				{
					this._ts_type_name = value;
				}
			}
		}
		
		[Column(Storage="_car_mark_model_name", DbType="VarChar(63) NOT NULL", CanBeNull=false)]
		public string car_mark_model_name
		{
			get
			{
				return this._car_mark_model_name;
			}
			set
			{
				if ((this._car_mark_model_name != value))
				{
					this._car_mark_model_name = value;
				}
			}
		}
		
		[Column(Storage="_car_mark_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_mark_id
		{
			get
			{
				return this._car_mark_id;
			}
			set
			{
				if ((this._car_mark_id != value))
				{
					this._car_mark_id = value;
				}
			}
		}
		
		[Column(Storage="_car_model_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_model_id
		{
			get
			{
				return this._car_model_id;
			}
			set
			{
				if ((this._car_model_id != value))
				{
					this._car_model_id = value;
				}
			}
		}
		
		[Column(Storage="_employee_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this._employee_id = value;
				}
			}
		}
		
		[Column(Storage="_FIO", DbType="VarChar(105)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this._FIO = value;
				}
			}
		}
		
		[Column(Storage="_car_state_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> car_state_id
		{
			get
			{
				return this._car_state_id;
			}
			set
			{
				if ((this._car_state_id != value))
				{
					this._car_state_id = value;
				}
			}
		}
		
		[Column(Storage="_car_state_name", DbType="VarChar(30)")]
		public string car_state_name
		{
			get
			{
				return this._car_state_name;
			}
			set
			{
				if ((this._car_state_name != value))
				{
					this._car_state_name = value;
				}
			}
		}
		
		[Column(Storage="_car_type_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_type_id
		{
			get
			{
				return this._car_type_id;
			}
			set
			{
				if ((this._car_type_id != value))
				{
					this._car_type_id = value;
				}
			}
		}
		
		[Column(Storage="_run", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> run
		{
			get
			{
				return this._run;
			}
			set
			{
				if ((this._run != value))
				{
					this._run = value;
				}
			}
		}
		
		[Column(Storage="_last_ts_type_master_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_ts_type_master_id
		{
			get
			{
				return this._last_ts_type_master_id;
			}
			set
			{
				if ((this._last_ts_type_master_id != value))
				{
					this._last_ts_type_master_id = value;
				}
			}
		}
		
		[Column(Storage="_edit_state", DbType="VarChar(1) NOT NULL")]
		public char edit_state
		{
			get
			{
				return this._edit_state;
			}
			set
			{
				if ((this._edit_state != value))
				{
					this._edit_state = value;
				}
			}
		}
		
		[Column(Storage="_fuel_start_left", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> fuel_start_left
		{
			get
			{
				return this._fuel_start_left;
			}
			set
			{
				if ((this._fuel_start_left != value))
				{
					this._fuel_start_left = value;
				}
			}
		}
		
		[Column(Storage="_fuel_end_left", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> fuel_end_left
		{
			get
			{
				return this._fuel_end_left;
			}
			set
			{
				if ((this._fuel_end_left != value))
				{
					this._fuel_end_left = value;
				}
			}
		}
		
		[Column(Storage="_speedometer_start_indctn", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> speedometer_start_indctn
		{
			get
			{
				return this._speedometer_start_indctn;
			}
			set
			{
				if ((this._speedometer_start_indctn != value))
				{
					this._speedometer_start_indctn = value;
				}
			}
		}
		
		[Column(Storage="_speedometer_end_indctn", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> speedometer_end_indctn
		{
			get
			{
				return this._speedometer_end_indctn;
			}
			set
			{
				if ((this._speedometer_end_indctn != value))
				{
					this._speedometer_end_indctn = value;
				}
			}
		}
		
		[Column(Storage="_sent_to", DbType="VarChar(1) NOT NULL")]
		public char sent_to
		{
			get
			{
				return this._sent_to;
			}
			set
			{
				if ((this._sent_to != value))
				{
					this._sent_to = value;
				}
			}
		}
		
		[Column(Storage="_last_run", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_run
		{
			get
			{
				return this._last_run;
			}
			set
			{
				if ((this._last_run != value))
				{
					this._last_run = value;
				}
			}
		}
		
		[Column(Storage="_overrun", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> overrun
		{
			get
			{
				return this._overrun;
			}
			set
			{
				if ((this._overrun != value))
				{
					this._overrun = value;
				}
			}
		}
		
		[Column(Storage="_in_tolerance", DbType="Int NOT NULL")]
		public int in_tolerance
		{
			get
			{
				return this._in_tolerance;
			}
			set
			{
				if ((this._in_tolerance != value))
				{
					this._in_tolerance = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_route_detail_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ts_type_route_detail_id
		{
			get
			{
				return this._ts_type_route_detail_id;
			}
			set
			{
				if ((this._ts_type_route_detail_id != value))
				{
					this._ts_type_route_detail_id = value;
				}
			}
		}
		
		[Column(Storage="_last_ts_type_route_detail_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_ts_type_route_detail_id
		{
			get
			{
				return this._last_ts_type_route_detail_id;
			}
			set
			{
				if ((this._last_ts_type_route_detail_id != value))
				{
					this._last_ts_type_route_detail_id = value;
				}
			}
		}
		
		[Column(Storage="_addtnl_ts", DbType="Int")]
		public System.Nullable<int> addtnl_ts
		{
			get
			{
				return this._addtnl_ts;
			}
			set
			{
				if ((this._addtnl_ts != value))
				{
					this._addtnl_ts = value;
				}
			}
		}
	}
	
	public partial class uspVCAR_CONDITION_SelectFreightResult
	{
		
		private decimal _id;
		
		private byte _sys_status;
		
		private string _sys_comment;
		
		private System.DateTime _sys_date_modified;
		
		private System.DateTime _sys_date_created;
		
		private string _sys_user_modified;
		
		private string _sys_user_created;
		
		private decimal _car_id;
		
		private string _state_number;
		
		private System.Nullable<decimal> _ts_type_master_id;
		
		private string _ts_type_name;
		
		private string _car_mark_model_name;
		
		private decimal _car_mark_id;
		
		private decimal _car_model_id;
		
		private System.Nullable<decimal> _employee_id;
		
		private string _FIO;
		
		private System.Nullable<decimal> _car_state_id;
		
		private string _car_state_name;
		
		private decimal _car_type_id;
		
		private System.Nullable<decimal> _run;
		
		private System.Nullable<decimal> _last_ts_type_master_id;
		
		private char _edit_state;
		
		private System.Nullable<decimal> _fuel_start_left;
		
		private System.Nullable<decimal> _fuel_end_left;
		
		private System.Nullable<decimal> _speedometer_start_indctn;
		
		private System.Nullable<decimal> _speedometer_end_indctn;
		
		private char _sent_to;
		
		private System.Nullable<decimal> _last_run;
		
		private System.Nullable<decimal> _overrun;
		
		private int _in_tolerance;
		
		private System.Nullable<decimal> _ts_type_route_detail_id;
		
		private System.Nullable<decimal> _last_ts_type_route_detail_id;
		
		private System.Nullable<int> _addtnl_ts;
		
		public uspVCAR_CONDITION_SelectFreightResult()
		{
		}
		
		[Column(Storage="_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this._id = value;
				}
			}
		}
		
		[Column(Storage="_sys_status", DbType="TinyInt NOT NULL")]
		public byte sys_status
		{
			get
			{
				return this._sys_status;
			}
			set
			{
				if ((this._sys_status != value))
				{
					this._sys_status = value;
				}
			}
		}
		
		[Column(Storage="_sys_comment", DbType="VarChar(2000) NOT NULL", CanBeNull=false)]
		public string sys_comment
		{
			get
			{
				return this._sys_comment;
			}
			set
			{
				if ((this._sys_comment != value))
				{
					this._sys_comment = value;
				}
			}
		}
		
		[Column(Storage="_sys_date_modified", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_modified
		{
			get
			{
				return this._sys_date_modified;
			}
			set
			{
				if ((this._sys_date_modified != value))
				{
					this._sys_date_modified = value;
				}
			}
		}
		
		[Column(Storage="_sys_date_created", DbType="DateTime NOT NULL")]
		public System.DateTime sys_date_created
		{
			get
			{
				return this._sys_date_created;
			}
			set
			{
				if ((this._sys_date_created != value))
				{
					this._sys_date_created = value;
				}
			}
		}
		
		[Column(Storage="_sys_user_modified", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_modified
		{
			get
			{
				return this._sys_user_modified;
			}
			set
			{
				if ((this._sys_user_modified != value))
				{
					this._sys_user_modified = value;
				}
			}
		}
		
		[Column(Storage="_sys_user_created", DbType="VarChar(30) NOT NULL", CanBeNull=false)]
		public string sys_user_created
		{
			get
			{
				return this._sys_user_created;
			}
			set
			{
				if ((this._sys_user_created != value))
				{
					this._sys_user_created = value;
				}
			}
		}
		
		[Column(Storage="_car_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_id
		{
			get
			{
				return this._car_id;
			}
			set
			{
				if ((this._car_id != value))
				{
					this._car_id = value;
				}
			}
		}
		
		[Column(Storage="_state_number", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string state_number
		{
			get
			{
				return this._state_number;
			}
			set
			{
				if ((this._state_number != value))
				{
					this._state_number = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_master_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ts_type_master_id
		{
			get
			{
				return this._ts_type_master_id;
			}
			set
			{
				if ((this._ts_type_master_id != value))
				{
					this._ts_type_master_id = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_name", DbType="VarChar(53)")]
		public string ts_type_name
		{
			get
			{
				return this._ts_type_name;
			}
			set
			{
				if ((this._ts_type_name != value))
				{
					this._ts_type_name = value;
				}
			}
		}
		
		[Column(Storage="_car_mark_model_name", DbType="VarChar(63) NOT NULL", CanBeNull=false)]
		public string car_mark_model_name
		{
			get
			{
				return this._car_mark_model_name;
			}
			set
			{
				if ((this._car_mark_model_name != value))
				{
					this._car_mark_model_name = value;
				}
			}
		}
		
		[Column(Storage="_car_mark_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_mark_id
		{
			get
			{
				return this._car_mark_id;
			}
			set
			{
				if ((this._car_mark_id != value))
				{
					this._car_mark_id = value;
				}
			}
		}
		
		[Column(Storage="_car_model_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_model_id
		{
			get
			{
				return this._car_model_id;
			}
			set
			{
				if ((this._car_model_id != value))
				{
					this._car_model_id = value;
				}
			}
		}
		
		[Column(Storage="_employee_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> employee_id
		{
			get
			{
				return this._employee_id;
			}
			set
			{
				if ((this._employee_id != value))
				{
					this._employee_id = value;
				}
			}
		}
		
		[Column(Storage="_FIO", DbType="VarChar(105)")]
		public string FIO
		{
			get
			{
				return this._FIO;
			}
			set
			{
				if ((this._FIO != value))
				{
					this._FIO = value;
				}
			}
		}
		
		[Column(Storage="_car_state_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> car_state_id
		{
			get
			{
				return this._car_state_id;
			}
			set
			{
				if ((this._car_state_id != value))
				{
					this._car_state_id = value;
				}
			}
		}
		
		[Column(Storage="_car_state_name", DbType="VarChar(30)")]
		public string car_state_name
		{
			get
			{
				return this._car_state_name;
			}
			set
			{
				if ((this._car_state_name != value))
				{
					this._car_state_name = value;
				}
			}
		}
		
		[Column(Storage="_car_type_id", DbType="Decimal(0,0) NOT NULL")]
		public decimal car_type_id
		{
			get
			{
				return this._car_type_id;
			}
			set
			{
				if ((this._car_type_id != value))
				{
					this._car_type_id = value;
				}
			}
		}
		
		[Column(Storage="_run", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> run
		{
			get
			{
				return this._run;
			}
			set
			{
				if ((this._run != value))
				{
					this._run = value;
				}
			}
		}
		
		[Column(Storage="_last_ts_type_master_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_ts_type_master_id
		{
			get
			{
				return this._last_ts_type_master_id;
			}
			set
			{
				if ((this._last_ts_type_master_id != value))
				{
					this._last_ts_type_master_id = value;
				}
			}
		}
		
		[Column(Storage="_edit_state", DbType="VarChar(1) NOT NULL")]
		public char edit_state
		{
			get
			{
				return this._edit_state;
			}
			set
			{
				if ((this._edit_state != value))
				{
					this._edit_state = value;
				}
			}
		}
		
		[Column(Storage="_fuel_start_left", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> fuel_start_left
		{
			get
			{
				return this._fuel_start_left;
			}
			set
			{
				if ((this._fuel_start_left != value))
				{
					this._fuel_start_left = value;
				}
			}
		}
		
		[Column(Storage="_fuel_end_left", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> fuel_end_left
		{
			get
			{
				return this._fuel_end_left;
			}
			set
			{
				if ((this._fuel_end_left != value))
				{
					this._fuel_end_left = value;
				}
			}
		}
		
		[Column(Storage="_speedometer_start_indctn", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> speedometer_start_indctn
		{
			get
			{
				return this._speedometer_start_indctn;
			}
			set
			{
				if ((this._speedometer_start_indctn != value))
				{
					this._speedometer_start_indctn = value;
				}
			}
		}
		
		[Column(Storage="_speedometer_end_indctn", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> speedometer_end_indctn
		{
			get
			{
				return this._speedometer_end_indctn;
			}
			set
			{
				if ((this._speedometer_end_indctn != value))
				{
					this._speedometer_end_indctn = value;
				}
			}
		}
		
		[Column(Storage="_sent_to", DbType="VarChar(1) NOT NULL")]
		public char sent_to
		{
			get
			{
				return this._sent_to;
			}
			set
			{
				if ((this._sent_to != value))
				{
					this._sent_to = value;
				}
			}
		}
		
		[Column(Storage="_last_run", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_run
		{
			get
			{
				return this._last_run;
			}
			set
			{
				if ((this._last_run != value))
				{
					this._last_run = value;
				}
			}
		}
		
		[Column(Storage="_overrun", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> overrun
		{
			get
			{
				return this._overrun;
			}
			set
			{
				if ((this._overrun != value))
				{
					this._overrun = value;
				}
			}
		}
		
		[Column(Storage="_in_tolerance", DbType="Int NOT NULL")]
		public int in_tolerance
		{
			get
			{
				return this._in_tolerance;
			}
			set
			{
				if ((this._in_tolerance != value))
				{
					this._in_tolerance = value;
				}
			}
		}
		
		[Column(Storage="_ts_type_route_detail_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> ts_type_route_detail_id
		{
			get
			{
				return this._ts_type_route_detail_id;
			}
			set
			{
				if ((this._ts_type_route_detail_id != value))
				{
					this._ts_type_route_detail_id = value;
				}
			}
		}
		
		[Column(Storage="_last_ts_type_route_detail_id", DbType="Decimal(0,0)")]
		public System.Nullable<decimal> last_ts_type_route_detail_id
		{
			get
			{
				return this._last_ts_type_route_detail_id;
			}
			set
			{
				if ((this._last_ts_type_route_detail_id != value))
				{
					this._last_ts_type_route_detail_id = value;
				}
			}
		}
		
		[Column(Storage="_addtnl_ts", DbType="Int")]
		public System.Nullable<int> addtnl_ts
		{
			get
			{
				return this._addtnl_ts;
			}
			set
			{
				if ((this._addtnl_ts != value))
				{
					this._addtnl_ts = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
