//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Angel_to_001 {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ANGEL_TO_001_Last_ts_type")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ANGEL_TO_001_Last_ts_type : global::System.Data.DataSet {
        
        private uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ANGEL_TO_001_Last_ts_type() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected ANGEL_TO_001_Last_ts_type(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["uspVCAR_LAST_TS_TYPE_SelectByCar_Id"] != null)) {
                    base.Tables.Add(new uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable(ds.Tables["uspVCAR_LAST_TS_TYPE_SelectByCar_Id"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable uspVCAR_LAST_TS_TYPE_SelectByCar_Id {
            get {
                return this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ANGEL_TO_001_Last_ts_type cln = ((ANGEL_TO_001_Last_ts_type)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["uspVCAR_LAST_TS_TYPE_SelectByCar_Id"] != null)) {
                    base.Tables.Add(new uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable(ds.Tables["uspVCAR_LAST_TS_TYPE_SelectByCar_Id"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id = ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable)(base.Tables["uspVCAR_LAST_TS_TYPE_SelectByCar_Id"]));
            if ((initTable == true)) {
                if ((this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id != null)) {
                    this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ANGEL_TO_001_Last_ts_type";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ANGEL_TO_001_Last_ts_type.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id = new uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable();
            base.Tables.Add(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeuspVCAR_LAST_TS_TYPE_SelectByCar_Id() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ANGEL_TO_001_Last_ts_type ds = new ANGEL_TO_001_Last_ts_type();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEventHandler(object sender, uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable : global::System.Data.TypedTableBase<uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow> {
            
            private global::System.Data.DataColumn columnid;
            
            private global::System.Data.DataColumn columnsys_status;
            
            private global::System.Data.DataColumn columnsys_comment;
            
            private global::System.Data.DataColumn columnsys_date_modified;
            
            private global::System.Data.DataColumn columnsys_date_created;
            
            private global::System.Data.DataColumn columnsys_user_modified;
            
            private global::System.Data.DataColumn columnsys_user_created;
            
            private global::System.Data.DataColumn columncar_id;
            
            private global::System.Data.DataColumn columnlast_ts_type_master_id;
            
            private global::System.Data.DataColumn columnrun;
            
            private global::System.Data.DataColumn columnts_type_sname;
            
            private global::System.Data.DataColumn columncar_mark_id;
            
            private global::System.Data.DataColumn columncar_model_id;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable() {
                this.TableName = "uspVCAR_LAST_TS_TYPE_SelectByCar_Id";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_statusColumn {
                get {
                    return this.columnsys_status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_commentColumn {
                get {
                    return this.columnsys_comment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_date_modifiedColumn {
                get {
                    return this.columnsys_date_modified;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_date_createdColumn {
                get {
                    return this.columnsys_date_created;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_user_modifiedColumn {
                get {
                    return this.columnsys_user_modified;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_user_createdColumn {
                get {
                    return this.columnsys_user_created;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_idColumn {
                get {
                    return this.columncar_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn last_ts_type_master_idColumn {
                get {
                    return this.columnlast_ts_type_master_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn runColumn {
                get {
                    return this.columnrun;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn ts_type_snameColumn {
                get {
                    return this.columnts_type_sname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_mark_idColumn {
                get {
                    return this.columncar_mark_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_model_idColumn {
                get {
                    return this.columncar_model_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow this[int index] {
                get {
                    return ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(this.Rows[index]));
                }
            }
            
            public event uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEventHandler uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanging;
            
            public event uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEventHandler uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanged;
            
            public event uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEventHandler uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleting;
            
            public event uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEventHandler uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AdduspVCAR_LAST_TS_TYPE_SelectByCar_IdRow(uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow AdduspVCAR_LAST_TS_TYPE_SelectByCar_IdRow(decimal id, byte sys_status, string sys_comment, System.DateTime sys_date_modified, System.DateTime sys_date_created, string sys_user_modified, string sys_user_created, decimal car_id, decimal last_ts_type_master_id, decimal run, string ts_type_sname, decimal car_mark_id, decimal car_model_id) {
                uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow rowuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow = ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        id,
                        sys_status,
                        sys_comment,
                        sys_date_modified,
                        sys_date_created,
                        sys_user_modified,
                        sys_user_created,
                        car_id,
                        last_ts_type_master_id,
                        run,
                        ts_type_sname,
                        car_mark_id,
                        car_model_id};
                rowuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow);
                return rowuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable cln = ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnid = base.Columns["id"];
                this.columnsys_status = base.Columns["sys_status"];
                this.columnsys_comment = base.Columns["sys_comment"];
                this.columnsys_date_modified = base.Columns["sys_date_modified"];
                this.columnsys_date_created = base.Columns["sys_date_created"];
                this.columnsys_user_modified = base.Columns["sys_user_modified"];
                this.columnsys_user_created = base.Columns["sys_user_created"];
                this.columncar_id = base.Columns["car_id"];
                this.columnlast_ts_type_master_id = base.Columns["last_ts_type_master_id"];
                this.columnrun = base.Columns["run"];
                this.columnts_type_sname = base.Columns["ts_type_sname"];
                this.columncar_mark_id = base.Columns["car_mark_id"];
                this.columncar_model_id = base.Columns["car_model_id"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnid = new global::System.Data.DataColumn("id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columnsys_status = new global::System.Data.DataColumn("sys_status", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_status);
                this.columnsys_comment = new global::System.Data.DataColumn("sys_comment", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_comment);
                this.columnsys_date_modified = new global::System.Data.DataColumn("sys_date_modified", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_date_modified);
                this.columnsys_date_created = new global::System.Data.DataColumn("sys_date_created", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_date_created);
                this.columnsys_user_modified = new global::System.Data.DataColumn("sys_user_modified", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_user_modified);
                this.columnsys_user_created = new global::System.Data.DataColumn("sys_user_created", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_user_created);
                this.columncar_id = new global::System.Data.DataColumn("car_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_id);
                this.columnlast_ts_type_master_id = new global::System.Data.DataColumn("last_ts_type_master_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnlast_ts_type_master_id);
                this.columnrun = new global::System.Data.DataColumn("run", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrun);
                this.columnts_type_sname = new global::System.Data.DataColumn("ts_type_sname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnts_type_sname);
                this.columncar_mark_id = new global::System.Data.DataColumn("car_mark_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_mark_id);
                this.columncar_model_id = new global::System.Data.DataColumn("car_model_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_model_id);
                this.columnsys_comment.MaxLength = 2000;
                this.columnsys_user_modified.MaxLength = 30;
                this.columnsys_user_created.MaxLength = 30;
                this.columnts_type_sname.MaxLength = 30;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow NewuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow() {
                return ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanged != null)) {
                    this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanged(this, new uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent(((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanging != null)) {
                    this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChanging(this, new uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent(((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleted != null)) {
                    this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleted(this, new uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent(((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleting != null)) {
                    this.uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowDeleting(this, new uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent(((uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveuspVCAR_LAST_TS_TYPE_SelectByCar_IdRow(uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ANGEL_TO_001_Last_ts_type ds = new ANGEL_TO_001_Last_ts_type();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow : global::System.Data.DataRow {
            
            private uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id = ((uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal id {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'id\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte sys_status {
                get {
                    try {
                        return ((byte)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_status\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\' " +
                                "is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_comment {
                get {
                    try {
                        return ((string)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_commentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_comment\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_commentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime sys_date_modified {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_modifiedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_date_modified\' in table \'uspVCAR_LAST_TS_TYPE_SelectByC" +
                                "ar_Id\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_modifiedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime sys_date_created {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_createdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_date_created\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCa" +
                                "r_Id\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_createdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_user_modified {
                get {
                    try {
                        return ((string)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_modifiedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_user_modified\' in table \'uspVCAR_LAST_TS_TYPE_SelectByC" +
                                "ar_Id\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_modifiedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_user_created {
                get {
                    try {
                        return ((string)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_createdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_user_created\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCa" +
                                "r_Id\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_createdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal car_id {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_id\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal last_ts_type_master_id {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.last_ts_type_master_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'last_ts_type_master_id\' in table \'uspVCAR_LAST_TS_TYPE_Sele" +
                                "ctByCar_Id\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.last_ts_type_master_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal run {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.runColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'run\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.runColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string ts_type_sname {
                get {
                    try {
                        return ((string)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.ts_type_snameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'ts_type_sname\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_I" +
                                "d\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.ts_type_snameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal car_mark_id {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_mark_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_mark_id\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id\'" +
                                " is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_mark_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal car_model_id {
                get {
                    try {
                        return ((decimal)(this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_model_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_model_id\' in table \'uspVCAR_LAST_TS_TYPE_SelectByCar_Id" +
                                "\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_model_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_statusNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_statusNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_commentNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_commentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_commentNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_commentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_date_modifiedNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_modifiedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_date_modifiedNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_modifiedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_date_createdNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_createdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_date_createdNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_date_createdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_user_modifiedNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_modifiedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_user_modifiedNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_modifiedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_user_createdNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_createdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_user_createdNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.sys_user_createdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_idNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_idNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Islast_ts_type_master_idNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.last_ts_type_master_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setlast_ts_type_master_idNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.last_ts_type_master_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsrunNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.runColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetrunNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.runColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ists_type_snameNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.ts_type_snameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setts_type_snameNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.ts_type_snameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_mark_idNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_mark_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_mark_idNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_mark_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_model_idNull() {
                return this.IsNull(this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_model_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_model_idNull() {
                this[this.tableuspVCAR_LAST_TS_TYPE_SelectByCar_Id.car_model_idColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent : global::System.EventArgs {
            
            private uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdRowChangeEvent(uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public uspVCAR_LAST_TS_TYPE_SelectByCar_IdRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Angel_to_001.ANGEL_TO_001_Last_ts_typeTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class uspVCAR_LAST_TS_TYPE_SelectByCar_IdTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public uspVCAR_LAST_TS_TYPE_SelectByCar_IdTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "uspVCAR_LAST_TS_TYPE_SelectByCar_Id";
            tableMapping.ColumnMappings.Add("id", "id");
            tableMapping.ColumnMappings.Add("sys_status", "sys_status");
            tableMapping.ColumnMappings.Add("sys_comment", "sys_comment");
            tableMapping.ColumnMappings.Add("sys_date_modified", "sys_date_modified");
            tableMapping.ColumnMappings.Add("sys_date_created", "sys_date_created");
            tableMapping.ColumnMappings.Add("sys_user_modified", "sys_user_modified");
            tableMapping.ColumnMappings.Add("sys_user_created", "sys_user_created");
            tableMapping.ColumnMappings.Add("car_id", "car_id");
            tableMapping.ColumnMappings.Add("last_ts_type_master_id", "last_ts_type_master_id");
            tableMapping.ColumnMappings.Add("run", "run");
            tableMapping.ColumnMappings.Add("ts_type_sname", "ts_type_sname");
            tableMapping.ColumnMappings.Add("car_mark_id", "car_mark_id");
            tableMapping.ColumnMappings.Add("car_model_id", "car_model_id");
            this._adapter.TableMappings.Add(tableMapping);
            this._adapter.DeleteCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.DeleteCommand.Connection = this.Connection;
            this._adapter.DeleteCommand.CommandText = "dbo.uspVCAR_LAST_TS_TYPE_DeleteById";
            this._adapter.DeleteCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.InsertCommand.Connection = this.Connection;
            this._adapter.InsertCommand.CommandText = "dbo.uspVCAR_LAST_TS_TYPE_SaveById";
            this._adapter.InsertCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.InputOutput, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_date_created", global::System.Data.SqlDbType.DateTime, 8, global::System.Data.ParameterDirection.Input, 23, 3, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_last_ts_type_master_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "last_ts_type_master_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_run", global::System.Data.SqlDbType.Decimal, 9, global::System.Data.ParameterDirection.Input, 18, 9, "run", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sent_to", global::System.Data.SqlDbType.Char, 1, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_overrun", global::System.Data.SqlDbType.Decimal, 9, global::System.Data.ParameterDirection.Input, 18, 9, "run", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_comment", global::System.Data.SqlDbType.VarChar, 2000, global::System.Data.ParameterDirection.Input, 0, 0, "sys_comment", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_user", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.UpdateCommand.Connection = this.Connection;
            this._adapter.UpdateCommand.CommandText = "dbo.uspVCAR_LAST_TS_TYPE_SaveById";
            this._adapter.UpdateCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.InputOutput, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_date_created", global::System.Data.SqlDbType.DateTime, 8, global::System.Data.ParameterDirection.Input, 23, 3, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_last_ts_type_master_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "last_ts_type_master_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_run", global::System.Data.SqlDbType.Decimal, 9, global::System.Data.ParameterDirection.Input, 18, 9, "run", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sent_to", global::System.Data.SqlDbType.Char, 1, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_overrun", global::System.Data.SqlDbType.Decimal, 9, global::System.Data.ParameterDirection.Input, 18, 9, "run", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_comment", global::System.Data.SqlDbType.VarChar, 2000, global::System.Data.ParameterDirection.Input, 0, 0, "sys_comment", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_user", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::Angel_to_001.Properties.Settings.Default.ANGEL_TO_001_ConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "dbo.uspVCAR_LAST_TS_TYPE_SelectByCar_Id";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.StoredProcedure;
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(ANGEL_TO_001_Last_ts_type.uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable dataTable, global::System.Nullable<decimal> p_car_id) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((p_car_id.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[1].Value = ((decimal)(p_car_id.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual ANGEL_TO_001_Last_ts_type.uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable GetData(global::System.Nullable<decimal> p_car_id) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((p_car_id.HasValue == true)) {
                this.Adapter.SelectCommand.Parameters[1].Value = ((decimal)(p_car_id.Value));
            }
            else {
                this.Adapter.SelectCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            ANGEL_TO_001_Last_ts_type.uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable dataTable = new ANGEL_TO_001_Last_ts_type.uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(ANGEL_TO_001_Last_ts_type.uspVCAR_LAST_TS_TYPE_SelectByCar_IdDataTable dataTable) {
            return this.Adapter.Update(dataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(ANGEL_TO_001_Last_ts_type dataSet) {
            return this.Adapter.Update(dataSet, "uspVCAR_LAST_TS_TYPE_SelectByCar_Id");
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(global::System.Data.DataRow dataRow) {
            return this.Adapter.Update(new global::System.Data.DataRow[] {
                        dataRow});
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(global::System.Data.DataRow[] dataRows) {
            return this.Adapter.Update(dataRows);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Delete, true)]
        public virtual int Delete(global::System.Nullable<decimal> p_id) {
            if ((p_id.HasValue == true)) {
                this.Adapter.DeleteCommand.Parameters[1].Value = ((decimal)(p_id.Value));
            }
            else {
                this.Adapter.DeleteCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            global::System.Data.ConnectionState previousConnectionState = this.Adapter.DeleteCommand.Connection.State;
            if (((this.Adapter.DeleteCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                        != global::System.Data.ConnectionState.Open)) {
                this.Adapter.DeleteCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.DeleteCommand.ExecuteNonQuery();
                return returnValue;
            }
            finally {
                if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
                    this.Adapter.DeleteCommand.Connection.Close();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Insert, true)]
        public virtual int Insert(ref global::System.Nullable<decimal> p_id, global::System.Nullable<global::System.DateTime> p_date_created, global::System.Nullable<decimal> p_car_id, global::System.Nullable<decimal> p_last_ts_type_master_id, global::System.Nullable<decimal> p_run, string p_sent_to, global::System.Nullable<decimal> p_overrun, string p_sys_comment, string p_sys_user) {
            if ((p_id.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[1].Value = ((decimal)(p_id.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            if ((p_date_created.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[2].Value = ((System.DateTime)(p_date_created.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[2].Value = global::System.DBNull.Value;
            }
            if ((p_car_id.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[3].Value = ((decimal)(p_car_id.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[3].Value = global::System.DBNull.Value;
            }
            if ((p_last_ts_type_master_id.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[4].Value = ((decimal)(p_last_ts_type_master_id.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[4].Value = global::System.DBNull.Value;
            }
            if ((p_run.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[5].Value = ((decimal)(p_run.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[5].Value = global::System.DBNull.Value;
            }
            if ((p_sent_to == null)) {
                this.Adapter.InsertCommand.Parameters[6].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[6].Value = ((string)(p_sent_to));
            }
            if ((p_overrun.HasValue == true)) {
                this.Adapter.InsertCommand.Parameters[7].Value = ((decimal)(p_overrun.Value));
            }
            else {
                this.Adapter.InsertCommand.Parameters[7].Value = global::System.DBNull.Value;
            }
            if ((p_sys_comment == null)) {
                this.Adapter.InsertCommand.Parameters[8].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[8].Value = ((string)(p_sys_comment));
            }
            if ((p_sys_user == null)) {
                this.Adapter.InsertCommand.Parameters[9].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.InsertCommand.Parameters[9].Value = ((string)(p_sys_user));
            }
            global::System.Data.ConnectionState previousConnectionState = this.Adapter.InsertCommand.Connection.State;
            if (((this.Adapter.InsertCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                        != global::System.Data.ConnectionState.Open)) {
                this.Adapter.InsertCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.InsertCommand.ExecuteNonQuery();
                if (((this.Adapter.InsertCommand.Parameters[1].Value == null) 
                            || (this.Adapter.InsertCommand.Parameters[1].Value.GetType() == typeof(global::System.DBNull)))) {
                    p_id = new global::System.Nullable<decimal>();
                }
                else {
                    p_id = new global::System.Nullable<decimal>(((decimal)(this.Adapter.InsertCommand.Parameters[1].Value)));
                }
                return returnValue;
            }
            finally {
                if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
                    this.Adapter.InsertCommand.Connection.Close();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Update, true)]
        public virtual int Update(ref global::System.Nullable<decimal> p_id, global::System.Nullable<global::System.DateTime> p_date_created, global::System.Nullable<decimal> p_car_id, global::System.Nullable<decimal> p_last_ts_type_master_id, global::System.Nullable<decimal> p_run, string p_sent_to, global::System.Nullable<decimal> p_overrun, string p_sys_comment, string p_sys_user) {
            if ((p_id.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[1].Value = ((decimal)(p_id.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[1].Value = global::System.DBNull.Value;
            }
            if ((p_date_created.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[2].Value = ((System.DateTime)(p_date_created.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[2].Value = global::System.DBNull.Value;
            }
            if ((p_car_id.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[3].Value = ((decimal)(p_car_id.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[3].Value = global::System.DBNull.Value;
            }
            if ((p_last_ts_type_master_id.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[4].Value = ((decimal)(p_last_ts_type_master_id.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[4].Value = global::System.DBNull.Value;
            }
            if ((p_run.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[5].Value = ((decimal)(p_run.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[5].Value = global::System.DBNull.Value;
            }
            if ((p_sent_to == null)) {
                this.Adapter.UpdateCommand.Parameters[6].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[6].Value = ((string)(p_sent_to));
            }
            if ((p_overrun.HasValue == true)) {
                this.Adapter.UpdateCommand.Parameters[7].Value = ((decimal)(p_overrun.Value));
            }
            else {
                this.Adapter.UpdateCommand.Parameters[7].Value = global::System.DBNull.Value;
            }
            if ((p_sys_comment == null)) {
                this.Adapter.UpdateCommand.Parameters[8].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[8].Value = ((string)(p_sys_comment));
            }
            if ((p_sys_user == null)) {
                this.Adapter.UpdateCommand.Parameters[9].Value = global::System.DBNull.Value;
            }
            else {
                this.Adapter.UpdateCommand.Parameters[9].Value = ((string)(p_sys_user));
            }
            global::System.Data.ConnectionState previousConnectionState = this.Adapter.UpdateCommand.Connection.State;
            if (((this.Adapter.UpdateCommand.Connection.State & global::System.Data.ConnectionState.Open) 
                        != global::System.Data.ConnectionState.Open)) {
                this.Adapter.UpdateCommand.Connection.Open();
            }
            try {
                int returnValue = this.Adapter.UpdateCommand.ExecuteNonQuery();
                if (((this.Adapter.UpdateCommand.Parameters[1].Value == null) 
                            || (this.Adapter.UpdateCommand.Parameters[1].Value.GetType() == typeof(global::System.DBNull)))) {
                    p_id = new global::System.Nullable<decimal>();
                }
                else {
                    p_id = new global::System.Nullable<decimal>(((decimal)(this.Adapter.UpdateCommand.Parameters[1].Value)));
                }
                return returnValue;
            }
            finally {
                if ((previousConnectionState == global::System.Data.ConnectionState.Closed)) {
                    this.Adapter.UpdateCommand.Connection.Close();
                }
            }
        }
    }
}

#pragma warning restore 1591