//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.1433
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

#pragma warning disable 1591

namespace Angel_to_001 {
    
    
    /// <summary>
    ///Represents a strongly typed in-memory cache of data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.Serializable()]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedDataSetSchema")]
    [global::System.Xml.Serialization.XmlRootAttribute("ANGEL_TO_001_Ts_type_master")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.DataSet")]
    public partial class ANGEL_TO_001_Ts_type_master : global::System.Data.DataSet {
        
        private utfVCAR_TS_TYPE_MASTERDataTable tableutfVCAR_TS_TYPE_MASTER;
        
        private global::System.Data.SchemaSerializationMode _schemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public ANGEL_TO_001_Ts_type_master() {
            this.BeginInit();
            this.InitClass();
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            base.Relations.CollectionChanged += schemaChangedHandler;
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected ANGEL_TO_001_Ts_type_master(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                base(info, context, false) {
            if ((this.IsBinarySerialized(info, context) == true)) {
                this.InitVars(false);
                global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler1 = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
                this.Tables.CollectionChanged += schemaChangedHandler1;
                this.Relations.CollectionChanged += schemaChangedHandler1;
                return;
            }
            string strSchema = ((string)(info.GetValue("XmlSchema", typeof(string))));
            if ((this.DetermineSchemaSerializationMode(info, context) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
                if ((ds.Tables["utfVCAR_TS_TYPE_MASTER"] != null)) {
                    base.Tables.Add(new utfVCAR_TS_TYPE_MASTERDataTable(ds.Tables["utfVCAR_TS_TYPE_MASTER"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXmlSchema(new global::System.Xml.XmlTextReader(new global::System.IO.StringReader(strSchema)));
            }
            this.GetSerializationData(info, context);
            global::System.ComponentModel.CollectionChangeEventHandler schemaChangedHandler = new global::System.ComponentModel.CollectionChangeEventHandler(this.SchemaChanged);
            base.Tables.CollectionChanged += schemaChangedHandler;
            this.Relations.CollectionChanged += schemaChangedHandler;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Browsable(false)]
        [global::System.ComponentModel.DesignerSerializationVisibility(global::System.ComponentModel.DesignerSerializationVisibility.Content)]
        public utfVCAR_TS_TYPE_MASTERDataTable utfVCAR_TS_TYPE_MASTER {
            get {
                return this.tableutfVCAR_TS_TYPE_MASTER;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.BrowsableAttribute(true)]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Visible)]
        public override global::System.Data.SchemaSerializationMode SchemaSerializationMode {
            get {
                return this._schemaSerializationMode;
            }
            set {
                this._schemaSerializationMode = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataTableCollection Tables {
            get {
                return base.Tables;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.DesignerSerializationVisibilityAttribute(global::System.ComponentModel.DesignerSerializationVisibility.Hidden)]
        public new global::System.Data.DataRelationCollection Relations {
            get {
                return base.Relations;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void InitializeDerivedDataSet() {
            this.BeginInit();
            this.InitClass();
            this.EndInit();
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public override global::System.Data.DataSet Clone() {
            ANGEL_TO_001_Ts_type_master cln = ((ANGEL_TO_001_Ts_type_master)(base.Clone()));
            cln.InitVars();
            cln.SchemaSerializationMode = this.SchemaSerializationMode;
            return cln;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeTables() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override bool ShouldSerializeRelations() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override void ReadXmlSerializable(global::System.Xml.XmlReader reader) {
            if ((this.DetermineSchemaSerializationMode(reader) == global::System.Data.SchemaSerializationMode.IncludeSchema)) {
                this.Reset();
                global::System.Data.DataSet ds = new global::System.Data.DataSet();
                ds.ReadXml(reader);
                if ((ds.Tables["utfVCAR_TS_TYPE_MASTER"] != null)) {
                    base.Tables.Add(new utfVCAR_TS_TYPE_MASTERDataTable(ds.Tables["utfVCAR_TS_TYPE_MASTER"]));
                }
                this.DataSetName = ds.DataSetName;
                this.Prefix = ds.Prefix;
                this.Namespace = ds.Namespace;
                this.Locale = ds.Locale;
                this.CaseSensitive = ds.CaseSensitive;
                this.EnforceConstraints = ds.EnforceConstraints;
                this.Merge(ds, false, global::System.Data.MissingSchemaAction.Add);
                this.InitVars();
            }
            else {
                this.ReadXml(reader);
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected override global::System.Xml.Schema.XmlSchema GetSchemaSerializable() {
            global::System.IO.MemoryStream stream = new global::System.IO.MemoryStream();
            this.WriteXmlSchema(new global::System.Xml.XmlTextWriter(stream, null));
            stream.Position = 0;
            return global::System.Xml.Schema.XmlSchema.Read(new global::System.Xml.XmlTextReader(stream), null);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars() {
            this.InitVars(true);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal void InitVars(bool initTable) {
            this.tableutfVCAR_TS_TYPE_MASTER = ((utfVCAR_TS_TYPE_MASTERDataTable)(base.Tables["utfVCAR_TS_TYPE_MASTER"]));
            if ((initTable == true)) {
                if ((this.tableutfVCAR_TS_TYPE_MASTER != null)) {
                    this.tableutfVCAR_TS_TYPE_MASTER.InitVars();
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitClass() {
            this.DataSetName = "ANGEL_TO_001_Ts_type_master";
            this.Prefix = "";
            this.Namespace = "http://tempuri.org/ANGEL_TO_001_Ts_type_master.xsd";
            this.EnforceConstraints = true;
            this.SchemaSerializationMode = global::System.Data.SchemaSerializationMode.IncludeSchema;
            this.tableutfVCAR_TS_TYPE_MASTER = new utfVCAR_TS_TYPE_MASTERDataTable();
            base.Tables.Add(this.tableutfVCAR_TS_TYPE_MASTER);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private bool ShouldSerializeutfVCAR_TS_TYPE_MASTER() {
            return false;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void SchemaChanged(object sender, global::System.ComponentModel.CollectionChangeEventArgs e) {
            if ((e.Action == global::System.ComponentModel.CollectionChangeAction.Remove)) {
                this.InitVars();
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedDataSetSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
            ANGEL_TO_001_Ts_type_master ds = new ANGEL_TO_001_Ts_type_master();
            global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
            global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
            global::System.Xml.Schema.XmlSchemaAny any = new global::System.Xml.Schema.XmlSchemaAny();
            any.Namespace = ds.Namespace;
            sequence.Items.Add(any);
            type.Particle = sequence;
            global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
            if (xs.Contains(dsSchema.TargetNamespace)) {
                global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                try {
                    global::System.Xml.Schema.XmlSchema schema = null;
                    dsSchema.Write(s1);
                    for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                        schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                        s2.SetLength(0);
                        schema.Write(s2);
                        if ((s1.Length == s2.Length)) {
                            s1.Position = 0;
                            s2.Position = 0;
                            for (; ((s1.Position != s1.Length) 
                                        && (s1.ReadByte() == s2.ReadByte())); ) {
                                ;
                            }
                            if ((s1.Position == s1.Length)) {
                                return type;
                            }
                        }
                    }
                }
                finally {
                    if ((s1 != null)) {
                        s1.Close();
                    }
                    if ((s2 != null)) {
                        s2.Close();
                    }
                }
            }
            xs.Add(dsSchema);
            return type;
        }
        
        public delegate void utfVCAR_TS_TYPE_MASTERRowChangeEventHandler(object sender, utfVCAR_TS_TYPE_MASTERRowChangeEvent e);
        
        /// <summary>
        ///Represents the strongly named DataTable class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        [global::System.Serializable()]
        [global::System.Xml.Serialization.XmlSchemaProviderAttribute("GetTypedTableSchema")]
        public partial class utfVCAR_TS_TYPE_MASTERDataTable : global::System.Data.TypedTableBase<utfVCAR_TS_TYPE_MASTERRow> {
            
            private global::System.Data.DataColumn columnid;
            
            private global::System.Data.DataColumn columnsys_status;
            
            private global::System.Data.DataColumn columnsys_comment;
            
            private global::System.Data.DataColumn columnsys_date_modified;
            
            private global::System.Data.DataColumn columnsys_date_created;
            
            private global::System.Data.DataColumn columnsys_user_modified;
            
            private global::System.Data.DataColumn columnsys_user_created;
            
            private global::System.Data.DataColumn columnshort_name;
            
            private global::System.Data.DataColumn columnfull_name;
            
            private global::System.Data.DataColumn columnperiodicity;
            
            private global::System.Data.DataColumn columncar_mark_id;
            
            private global::System.Data.DataColumn columncar_mark_model_name;
            
            private global::System.Data.DataColumn columncar_model_id;
            
            private global::System.Data.DataColumn columntolerance;
            
            private global::System.Data.DataColumn columncar_mark_sname;
            
            private global::System.Data.DataColumn columncar_model_sname;
            
            private global::System.Data.DataColumn columnparent_id;
            
            private global::System.Data.DataColumn columnchild_ts_type_array;
            
            private global::System.Data.DataColumn columnrepair_type_master_kind_id;
            
            private global::System.Data.DataColumn columnrepair_type_master_kind_sname;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERDataTable() {
                this.TableName = "utfVCAR_TS_TYPE_MASTER";
                this.BeginInit();
                this.InitClass();
                this.EndInit();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal utfVCAR_TS_TYPE_MASTERDataTable(global::System.Data.DataTable table) {
                this.TableName = table.TableName;
                if ((table.CaseSensitive != table.DataSet.CaseSensitive)) {
                    this.CaseSensitive = table.CaseSensitive;
                }
                if ((table.Locale.ToString() != table.DataSet.Locale.ToString())) {
                    this.Locale = table.Locale;
                }
                if ((table.Namespace != table.DataSet.Namespace)) {
                    this.Namespace = table.Namespace;
                }
                this.Prefix = table.Prefix;
                this.MinimumCapacity = table.MinimumCapacity;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected utfVCAR_TS_TYPE_MASTERDataTable(global::System.Runtime.Serialization.SerializationInfo info, global::System.Runtime.Serialization.StreamingContext context) : 
                    base(info, context) {
                this.InitVars();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn idColumn {
                get {
                    return this.columnid;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_statusColumn {
                get {
                    return this.columnsys_status;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_commentColumn {
                get {
                    return this.columnsys_comment;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_date_modifiedColumn {
                get {
                    return this.columnsys_date_modified;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_date_createdColumn {
                get {
                    return this.columnsys_date_created;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_user_modifiedColumn {
                get {
                    return this.columnsys_user_modified;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn sys_user_createdColumn {
                get {
                    return this.columnsys_user_created;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn short_nameColumn {
                get {
                    return this.columnshort_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn full_nameColumn {
                get {
                    return this.columnfull_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn periodicityColumn {
                get {
                    return this.columnperiodicity;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_mark_idColumn {
                get {
                    return this.columncar_mark_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_mark_model_nameColumn {
                get {
                    return this.columncar_mark_model_name;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_model_idColumn {
                get {
                    return this.columncar_model_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn toleranceColumn {
                get {
                    return this.columntolerance;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_mark_snameColumn {
                get {
                    return this.columncar_mark_sname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn car_model_snameColumn {
                get {
                    return this.columncar_model_sname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn parent_idColumn {
                get {
                    return this.columnparent_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn child_ts_type_arrayColumn {
                get {
                    return this.columnchild_ts_type_array;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn repair_type_master_kind_idColumn {
                get {
                    return this.columnrepair_type_master_kind_id;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataColumn repair_type_master_kind_snameColumn {
                get {
                    return this.columnrepair_type_master_kind_sname;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            [global::System.ComponentModel.Browsable(false)]
            public int Count {
                get {
                    return this.Rows.Count;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERRow this[int index] {
                get {
                    return ((utfVCAR_TS_TYPE_MASTERRow)(this.Rows[index]));
                }
            }
            
            public event utfVCAR_TS_TYPE_MASTERRowChangeEventHandler utfVCAR_TS_TYPE_MASTERRowChanging;
            
            public event utfVCAR_TS_TYPE_MASTERRowChangeEventHandler utfVCAR_TS_TYPE_MASTERRowChanged;
            
            public event utfVCAR_TS_TYPE_MASTERRowChangeEventHandler utfVCAR_TS_TYPE_MASTERRowDeleting;
            
            public event utfVCAR_TS_TYPE_MASTERRowChangeEventHandler utfVCAR_TS_TYPE_MASTERRowDeleted;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void AddutfVCAR_TS_TYPE_MASTERRow(utfVCAR_TS_TYPE_MASTERRow row) {
                this.Rows.Add(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERRow AddutfVCAR_TS_TYPE_MASTERRow(
                        decimal id, 
                        byte sys_status, 
                        string sys_comment, 
                        System.DateTime sys_date_modified, 
                        System.DateTime sys_date_created, 
                        string sys_user_modified, 
                        string sys_user_created, 
                        string short_name, 
                        string full_name, 
                        int periodicity, 
                        decimal car_mark_id, 
                        string car_mark_model_name, 
                        decimal car_model_id, 
                        short tolerance, 
                        string car_mark_sname, 
                        string car_model_sname, 
                        decimal parent_id, 
                        string child_ts_type_array, 
                        decimal repair_type_master_kind_id, 
                        string repair_type_master_kind_sname) {
                utfVCAR_TS_TYPE_MASTERRow rowutfVCAR_TS_TYPE_MASTERRow = ((utfVCAR_TS_TYPE_MASTERRow)(this.NewRow()));
                object[] columnValuesArray = new object[] {
                        id,
                        sys_status,
                        sys_comment,
                        sys_date_modified,
                        sys_date_created,
                        sys_user_modified,
                        sys_user_created,
                        short_name,
                        full_name,
                        periodicity,
                        car_mark_id,
                        car_mark_model_name,
                        car_model_id,
                        tolerance,
                        car_mark_sname,
                        car_model_sname,
                        parent_id,
                        child_ts_type_array,
                        repair_type_master_kind_id,
                        repair_type_master_kind_sname};
                rowutfVCAR_TS_TYPE_MASTERRow.ItemArray = columnValuesArray;
                this.Rows.Add(rowutfVCAR_TS_TYPE_MASTERRow);
                return rowutfVCAR_TS_TYPE_MASTERRow;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public override global::System.Data.DataTable Clone() {
                utfVCAR_TS_TYPE_MASTERDataTable cln = ((utfVCAR_TS_TYPE_MASTERDataTable)(base.Clone()));
                cln.InitVars();
                return cln;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataTable CreateInstance() {
                return new utfVCAR_TS_TYPE_MASTERDataTable();
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal void InitVars() {
                this.columnid = base.Columns["id"];
                this.columnsys_status = base.Columns["sys_status"];
                this.columnsys_comment = base.Columns["sys_comment"];
                this.columnsys_date_modified = base.Columns["sys_date_modified"];
                this.columnsys_date_created = base.Columns["sys_date_created"];
                this.columnsys_user_modified = base.Columns["sys_user_modified"];
                this.columnsys_user_created = base.Columns["sys_user_created"];
                this.columnshort_name = base.Columns["short_name"];
                this.columnfull_name = base.Columns["full_name"];
                this.columnperiodicity = base.Columns["periodicity"];
                this.columncar_mark_id = base.Columns["car_mark_id"];
                this.columncar_mark_model_name = base.Columns["car_mark_model_name"];
                this.columncar_model_id = base.Columns["car_model_id"];
                this.columntolerance = base.Columns["tolerance"];
                this.columncar_mark_sname = base.Columns["car_mark_sname"];
                this.columncar_model_sname = base.Columns["car_model_sname"];
                this.columnparent_id = base.Columns["parent_id"];
                this.columnchild_ts_type_array = base.Columns["child_ts_type_array"];
                this.columnrepair_type_master_kind_id = base.Columns["repair_type_master_kind_id"];
                this.columnrepair_type_master_kind_sname = base.Columns["repair_type_master_kind_sname"];
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            private void InitClass() {
                this.columnid = new global::System.Data.DataColumn("id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnid);
                this.columnsys_status = new global::System.Data.DataColumn("sys_status", typeof(byte), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_status);
                this.columnsys_comment = new global::System.Data.DataColumn("sys_comment", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_comment);
                this.columnsys_date_modified = new global::System.Data.DataColumn("sys_date_modified", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_date_modified);
                this.columnsys_date_created = new global::System.Data.DataColumn("sys_date_created", typeof(global::System.DateTime), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_date_created);
                this.columnsys_user_modified = new global::System.Data.DataColumn("sys_user_modified", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_user_modified);
                this.columnsys_user_created = new global::System.Data.DataColumn("sys_user_created", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnsys_user_created);
                this.columnshort_name = new global::System.Data.DataColumn("short_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnshort_name);
                this.columnfull_name = new global::System.Data.DataColumn("full_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnfull_name);
                this.columnperiodicity = new global::System.Data.DataColumn("periodicity", typeof(int), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnperiodicity);
                this.columncar_mark_id = new global::System.Data.DataColumn("car_mark_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_mark_id);
                this.columncar_mark_model_name = new global::System.Data.DataColumn("car_mark_model_name", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_mark_model_name);
                this.columncar_model_id = new global::System.Data.DataColumn("car_model_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_model_id);
                this.columntolerance = new global::System.Data.DataColumn("tolerance", typeof(short), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columntolerance);
                this.columncar_mark_sname = new global::System.Data.DataColumn("car_mark_sname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_mark_sname);
                this.columncar_model_sname = new global::System.Data.DataColumn("car_model_sname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columncar_model_sname);
                this.columnparent_id = new global::System.Data.DataColumn("parent_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnparent_id);
                this.columnchild_ts_type_array = new global::System.Data.DataColumn("child_ts_type_array", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnchild_ts_type_array);
                this.columnrepair_type_master_kind_id = new global::System.Data.DataColumn("repair_type_master_kind_id", typeof(decimal), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrepair_type_master_kind_id);
                this.columnrepair_type_master_kind_sname = new global::System.Data.DataColumn("repair_type_master_kind_sname", typeof(string), null, global::System.Data.MappingType.Element);
                base.Columns.Add(this.columnrepair_type_master_kind_sname);
                this.columnsys_comment.MaxLength = 2000;
                this.columnsys_user_modified.MaxLength = 30;
                this.columnsys_user_created.MaxLength = 30;
                this.columnshort_name.MaxLength = 30;
                this.columnfull_name.MaxLength = 60;
                this.columncar_mark_model_name.MaxLength = 63;
                this.columncar_mark_sname.MaxLength = 30;
                this.columncar_model_sname.MaxLength = 30;
                this.columnrepair_type_master_kind_sname.MaxLength = 30;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERRow NewutfVCAR_TS_TYPE_MASTERRow() {
                return ((utfVCAR_TS_TYPE_MASTERRow)(this.NewRow()));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Data.DataRow NewRowFromBuilder(global::System.Data.DataRowBuilder builder) {
                return new utfVCAR_TS_TYPE_MASTERRow(builder);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override global::System.Type GetRowType() {
                return typeof(utfVCAR_TS_TYPE_MASTERRow);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanged(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanged(e);
                if ((this.utfVCAR_TS_TYPE_MASTERRowChanged != null)) {
                    this.utfVCAR_TS_TYPE_MASTERRowChanged(this, new utfVCAR_TS_TYPE_MASTERRowChangeEvent(((utfVCAR_TS_TYPE_MASTERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowChanging(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowChanging(e);
                if ((this.utfVCAR_TS_TYPE_MASTERRowChanging != null)) {
                    this.utfVCAR_TS_TYPE_MASTERRowChanging(this, new utfVCAR_TS_TYPE_MASTERRowChangeEvent(((utfVCAR_TS_TYPE_MASTERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleted(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleted(e);
                if ((this.utfVCAR_TS_TYPE_MASTERRowDeleted != null)) {
                    this.utfVCAR_TS_TYPE_MASTERRowDeleted(this, new utfVCAR_TS_TYPE_MASTERRowChangeEvent(((utfVCAR_TS_TYPE_MASTERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            protected override void OnRowDeleting(global::System.Data.DataRowChangeEventArgs e) {
                base.OnRowDeleting(e);
                if ((this.utfVCAR_TS_TYPE_MASTERRowDeleting != null)) {
                    this.utfVCAR_TS_TYPE_MASTERRowDeleting(this, new utfVCAR_TS_TYPE_MASTERRowChangeEvent(((utfVCAR_TS_TYPE_MASTERRow)(e.Row)), e.Action));
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void RemoveutfVCAR_TS_TYPE_MASTERRow(utfVCAR_TS_TYPE_MASTERRow row) {
                this.Rows.Remove(row);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public static global::System.Xml.Schema.XmlSchemaComplexType GetTypedTableSchema(global::System.Xml.Schema.XmlSchemaSet xs) {
                global::System.Xml.Schema.XmlSchemaComplexType type = new global::System.Xml.Schema.XmlSchemaComplexType();
                global::System.Xml.Schema.XmlSchemaSequence sequence = new global::System.Xml.Schema.XmlSchemaSequence();
                ANGEL_TO_001_Ts_type_master ds = new ANGEL_TO_001_Ts_type_master();
                global::System.Xml.Schema.XmlSchemaAny any1 = new global::System.Xml.Schema.XmlSchemaAny();
                any1.Namespace = "http://www.w3.org/2001/XMLSchema";
                any1.MinOccurs = new decimal(0);
                any1.MaxOccurs = decimal.MaxValue;
                any1.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any1);
                global::System.Xml.Schema.XmlSchemaAny any2 = new global::System.Xml.Schema.XmlSchemaAny();
                any2.Namespace = "urn:schemas-microsoft-com:xml-diffgram-v1";
                any2.MinOccurs = new decimal(1);
                any2.ProcessContents = global::System.Xml.Schema.XmlSchemaContentProcessing.Lax;
                sequence.Items.Add(any2);
                global::System.Xml.Schema.XmlSchemaAttribute attribute1 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute1.Name = "namespace";
                attribute1.FixedValue = ds.Namespace;
                type.Attributes.Add(attribute1);
                global::System.Xml.Schema.XmlSchemaAttribute attribute2 = new global::System.Xml.Schema.XmlSchemaAttribute();
                attribute2.Name = "tableTypeName";
                attribute2.FixedValue = "utfVCAR_TS_TYPE_MASTERDataTable";
                type.Attributes.Add(attribute2);
                type.Particle = sequence;
                global::System.Xml.Schema.XmlSchema dsSchema = ds.GetSchemaSerializable();
                if (xs.Contains(dsSchema.TargetNamespace)) {
                    global::System.IO.MemoryStream s1 = new global::System.IO.MemoryStream();
                    global::System.IO.MemoryStream s2 = new global::System.IO.MemoryStream();
                    try {
                        global::System.Xml.Schema.XmlSchema schema = null;
                        dsSchema.Write(s1);
                        for (global::System.Collections.IEnumerator schemas = xs.Schemas(dsSchema.TargetNamespace).GetEnumerator(); schemas.MoveNext(); ) {
                            schema = ((global::System.Xml.Schema.XmlSchema)(schemas.Current));
                            s2.SetLength(0);
                            schema.Write(s2);
                            if ((s1.Length == s2.Length)) {
                                s1.Position = 0;
                                s2.Position = 0;
                                for (; ((s1.Position != s1.Length) 
                                            && (s1.ReadByte() == s2.ReadByte())); ) {
                                    ;
                                }
                                if ((s1.Position == s1.Length)) {
                                    return type;
                                }
                            }
                        }
                    }
                    finally {
                        if ((s1 != null)) {
                            s1.Close();
                        }
                        if ((s2 != null)) {
                            s2.Close();
                        }
                    }
                }
                xs.Add(dsSchema);
                return type;
            }
        }
        
        /// <summary>
        ///Represents strongly named DataRow class.
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public partial class utfVCAR_TS_TYPE_MASTERRow : global::System.Data.DataRow {
            
            private utfVCAR_TS_TYPE_MASTERDataTable tableutfVCAR_TS_TYPE_MASTER;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            internal utfVCAR_TS_TYPE_MASTERRow(global::System.Data.DataRowBuilder rb) : 
                    base(rb) {
                this.tableutfVCAR_TS_TYPE_MASTER = ((utfVCAR_TS_TYPE_MASTERDataTable)(this.Table));
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal id {
                get {
                    try {
                        return ((decimal)(this[this.tableutfVCAR_TS_TYPE_MASTER.idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'id\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public byte sys_status {
                get {
                    try {
                        return ((byte)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_statusColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_status\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_statusColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_comment {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_commentColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_comment\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_commentColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime sys_date_modified {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_modifiedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_date_modified\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_modifiedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public System.DateTime sys_date_created {
                get {
                    try {
                        return ((global::System.DateTime)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_createdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_date_created\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_createdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_user_modified {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_modifiedColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_user_modified\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBN" +
                                "ull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_modifiedColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string sys_user_created {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_createdColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'sys_user_created\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNu" +
                                "ll.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_createdColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string short_name {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.short_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'short_name\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.short_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string full_name {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.full_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'full_name\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.full_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public int periodicity {
                get {
                    try {
                        return ((int)(this[this.tableutfVCAR_TS_TYPE_MASTER.periodicityColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'periodicity\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.periodicityColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal car_mark_id {
                get {
                    try {
                        return ((decimal)(this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_mark_id\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string car_mark_model_name {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_model_nameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_mark_model_name\' in table \'utfVCAR_TS_TYPE_MASTER\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_model_nameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal car_model_id {
                get {
                    try {
                        return ((decimal)(this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_model_id\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public short tolerance {
                get {
                    try {
                        return ((short)(this[this.tableutfVCAR_TS_TYPE_MASTER.toleranceColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'tolerance\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.toleranceColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string car_mark_sname {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_snameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_mark_sname\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull" +
                                ".", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_snameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string car_model_sname {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_snameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'car_model_sname\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNul" +
                                "l.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_snameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal parent_id {
                get {
                    try {
                        return ((decimal)(this[this.tableutfVCAR_TS_TYPE_MASTER.parent_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'parent_id\' in table \'utfVCAR_TS_TYPE_MASTER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.parent_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string child_ts_type_array {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.child_ts_type_arrayColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'child_ts_type_array\' in table \'utfVCAR_TS_TYPE_MASTER\' is D" +
                                "BNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.child_ts_type_arrayColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public decimal repair_type_master_kind_id {
                get {
                    try {
                        return ((decimal)(this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_idColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'repair_type_master_kind_id\' in table \'utfVCAR_TS_TYPE_MASTE" +
                                "R\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_idColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public string repair_type_master_kind_sname {
                get {
                    try {
                        return ((string)(this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_snameColumn]));
                    }
                    catch (global::System.InvalidCastException e) {
                        throw new global::System.Data.StrongTypingException("The value for column \'repair_type_master_kind_sname\' in table \'utfVCAR_TS_TYPE_MA" +
                                "STER\' is DBNull.", e);
                    }
                }
                set {
                    this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_snameColumn] = value;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsidNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetidNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_statusNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_statusColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_statusNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_statusColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_commentNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_commentColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_commentNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_commentColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_date_modifiedNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_date_modifiedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_date_modifiedNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_modifiedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_date_createdNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_date_createdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_date_createdNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_date_createdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_user_modifiedNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_user_modifiedColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_user_modifiedNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_modifiedColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Issys_user_createdNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.sys_user_createdColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setsys_user_createdNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.sys_user_createdColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isshort_nameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.short_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setshort_nameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.short_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isfull_nameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.full_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setfull_nameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.full_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IsperiodicityNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.periodicityColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SetperiodicityNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.periodicityColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_mark_idNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.car_mark_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_mark_idNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_mark_model_nameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.car_mark_model_nameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_mark_model_nameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_model_nameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_model_idNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.car_model_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_model_idNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool IstoleranceNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.toleranceColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void SettoleranceNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.toleranceColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_mark_snameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.car_mark_snameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_mark_snameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.car_mark_snameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Iscar_model_snameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.car_model_snameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setcar_model_snameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.car_model_snameColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isparent_idNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.parent_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setparent_idNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.parent_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Ischild_ts_type_arrayNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.child_ts_type_arrayColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setchild_ts_type_arrayNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.child_ts_type_arrayColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrepair_type_master_kind_idNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_idColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrepair_type_master_kind_idNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_idColumn] = global::System.Convert.DBNull;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public bool Isrepair_type_master_kind_snameNull() {
                return this.IsNull(this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_snameColumn);
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public void Setrepair_type_master_kind_snameNull() {
                this[this.tableutfVCAR_TS_TYPE_MASTER.repair_type_master_kind_snameColumn] = global::System.Convert.DBNull;
            }
        }
        
        /// <summary>
        ///Row event argument class
        ///</summary>
        [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
        public class utfVCAR_TS_TYPE_MASTERRowChangeEvent : global::System.EventArgs {
            
            private utfVCAR_TS_TYPE_MASTERRow eventRow;
            
            private global::System.Data.DataRowAction eventAction;
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERRowChangeEvent(utfVCAR_TS_TYPE_MASTERRow row, global::System.Data.DataRowAction action) {
                this.eventRow = row;
                this.eventAction = action;
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public utfVCAR_TS_TYPE_MASTERRow Row {
                get {
                    return this.eventRow;
                }
            }
            
            [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
            public global::System.Data.DataRowAction Action {
                get {
                    return this.eventAction;
                }
            }
        }
    }
}
namespace Angel_to_001.ANGEL_TO_001_Ts_type_masterTableAdapters {
    
    
    /// <summary>
    ///Represents the connection and commands used to retrieve and save data.
    ///</summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Data.Design.TypedDataSetGenerator", "2.0.0.0")]
    [global::System.ComponentModel.DesignerCategoryAttribute("code")]
    [global::System.ComponentModel.ToolboxItem(true)]
    [global::System.ComponentModel.DataObjectAttribute(true)]
    [global::System.ComponentModel.DesignerAttribute("Microsoft.VSDesigner.DataSource.Design.TableAdapterDesigner, Microsoft.VSDesigner" +
        ", Version=8.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a")]
    [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
    public partial class utfVCAR_TS_TYPE_MASTERTableAdapter : global::System.ComponentModel.Component {
        
        private global::System.Data.SqlClient.SqlDataAdapter _adapter;
        
        private global::System.Data.SqlClient.SqlConnection _connection;
        
        private global::System.Data.SqlClient.SqlCommand[] _commandCollection;
        
        private bool _clearBeforeFill;
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public utfVCAR_TS_TYPE_MASTERTableAdapter() {
            this.ClearBeforeFill = true;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private global::System.Data.SqlClient.SqlDataAdapter Adapter {
            get {
                if ((this._adapter == null)) {
                    this.InitAdapter();
                }
                return this._adapter;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        internal global::System.Data.SqlClient.SqlConnection Connection {
            get {
                if ((this._connection == null)) {
                    this.InitConnection();
                }
                return this._connection;
            }
            set {
                this._connection = value;
                if ((this.Adapter.InsertCommand != null)) {
                    this.Adapter.InsertCommand.Connection = value;
                }
                if ((this.Adapter.DeleteCommand != null)) {
                    this.Adapter.DeleteCommand.Connection = value;
                }
                if ((this.Adapter.UpdateCommand != null)) {
                    this.Adapter.UpdateCommand.Connection = value;
                }
                for (int i = 0; (i < this.CommandCollection.Length); i = (i + 1)) {
                    if ((this.CommandCollection[i] != null)) {
                        ((global::System.Data.SqlClient.SqlCommand)(this.CommandCollection[i])).Connection = value;
                    }
                }
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        protected global::System.Data.SqlClient.SqlCommand[] CommandCollection {
            get {
                if ((this._commandCollection == null)) {
                    this.InitCommandCollection();
                }
                return this._commandCollection;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        public bool ClearBeforeFill {
            get {
                return this._clearBeforeFill;
            }
            set {
                this._clearBeforeFill = value;
            }
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitAdapter() {
            this._adapter = new global::System.Data.SqlClient.SqlDataAdapter();
            global::System.Data.Common.DataTableMapping tableMapping = new global::System.Data.Common.DataTableMapping();
            tableMapping.SourceTable = "Table";
            tableMapping.DataSetTable = "utfVCAR_TS_TYPE_MASTER";
            tableMapping.ColumnMappings.Add("id", "id");
            tableMapping.ColumnMappings.Add("sys_status", "sys_status");
            tableMapping.ColumnMappings.Add("sys_comment", "sys_comment");
            tableMapping.ColumnMappings.Add("sys_date_modified", "sys_date_modified");
            tableMapping.ColumnMappings.Add("sys_date_created", "sys_date_created");
            tableMapping.ColumnMappings.Add("sys_user_modified", "sys_user_modified");
            tableMapping.ColumnMappings.Add("sys_user_created", "sys_user_created");
            tableMapping.ColumnMappings.Add("short_name", "short_name");
            tableMapping.ColumnMappings.Add("full_name", "full_name");
            tableMapping.ColumnMappings.Add("periodicity", "periodicity");
            tableMapping.ColumnMappings.Add("car_mark_id", "car_mark_id");
            tableMapping.ColumnMappings.Add("car_mark_model_name", "car_mark_model_name");
            tableMapping.ColumnMappings.Add("car_model_id", "car_model_id");
            tableMapping.ColumnMappings.Add("tolerance", "tolerance");
            tableMapping.ColumnMappings.Add("car_mark_sname", "car_mark_sname");
            tableMapping.ColumnMappings.Add("car_model_sname", "car_model_sname");
            tableMapping.ColumnMappings.Add("repair_type_master_kind_id", "repair_type_master_kind_id");
            tableMapping.ColumnMappings.Add("repair_type_master_kind_sname", "repair_type_master_kind_sname");
            this._adapter.TableMappings.Add(tableMapping);
            this._adapter.DeleteCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.DeleteCommand.Connection = this.Connection;
            this._adapter.DeleteCommand.CommandText = "dbo.uspVCAR_TS_TYPE_MASTER_DeleteById";
            this._adapter.DeleteCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_comment", global::System.Data.SqlDbType.VarChar, 2000, global::System.Data.ParameterDirection.Input, 0, 0, "sys_comment", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.DeleteCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_user", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "sys_user_modified", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.InsertCommand.Connection = this.Connection;
            this._adapter.InsertCommand.CommandText = "dbo.uspVCAR_TS_TYPE_MASTER_SaveById";
            this._adapter.InsertCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.InputOutput, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_short_name", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "short_name", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_full_name", global::System.Data.SqlDbType.VarChar, 60, global::System.Data.ParameterDirection.Input, 0, 0, "full_name", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_periodicity", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 10, 0, "periodicity", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_mark_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_mark_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_model_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_model_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_tolerance", global::System.Data.SqlDbType.SmallInt, 2, global::System.Data.ParameterDirection.Input, 5, 0, "tolerance", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_parent_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "parent_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_code", global::System.Data.SqlDbType.VarChar, 20, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_time_to_repair_in_minutes", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 10, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_repair_type_master_kind_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "repair_type_master_kind_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_comment", global::System.Data.SqlDbType.VarChar, 2000, global::System.Data.ParameterDirection.Input, 0, 0, "sys_comment", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.InsertCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_user", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "sys_user_modified", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand = new global::System.Data.SqlClient.SqlCommand();
            this._adapter.UpdateCommand.Connection = this.Connection;
            this._adapter.UpdateCommand.CommandText = "dbo.uspVCAR_TS_TYPE_MASTER_SaveById";
            this._adapter.UpdateCommand.CommandType = global::System.Data.CommandType.StoredProcedure;
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.InputOutput, 38, 0, "id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_short_name", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "short_name", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_full_name", global::System.Data.SqlDbType.VarChar, 60, global::System.Data.ParameterDirection.Input, 0, 0, "full_name", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_periodicity", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 10, 0, "periodicity", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_mark_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_mark_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_car_model_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "car_model_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_tolerance", global::System.Data.SqlDbType.SmallInt, 2, global::System.Data.ParameterDirection.Input, 5, 0, "tolerance", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_parent_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "parent_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_code", global::System.Data.SqlDbType.VarChar, 20, global::System.Data.ParameterDirection.Input, 0, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_time_to_repair_in_minutes", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.Input, 10, 0, "", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_repair_type_master_kind_id", global::System.Data.SqlDbType.Decimal, 17, global::System.Data.ParameterDirection.Input, 38, 0, "repair_type_master_kind_id", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_comment", global::System.Data.SqlDbType.VarChar, 2000, global::System.Data.ParameterDirection.Input, 0, 0, "sys_comment", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
            this._adapter.UpdateCommand.Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@p_sys_user", global::System.Data.SqlDbType.VarChar, 30, global::System.Data.ParameterDirection.Input, 0, 0, "sys_user_modified", global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitConnection() {
            this._connection = new global::System.Data.SqlClient.SqlConnection();
            this._connection.ConnectionString = global::Angel_to_001.Properties.Settings.Default.ANGEL_TO_001_ConnectionString;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        private void InitCommandCollection() {
            this._commandCollection = new global::System.Data.SqlClient.SqlCommand[1];
            this._commandCollection[0] = new global::System.Data.SqlClient.SqlCommand();
            this._commandCollection[0].Connection = this.Connection;
            this._commandCollection[0].CommandText = "dbo.uspVCAR_TS_TYPE_MASTER_SelectAll";
            this._commandCollection[0].CommandType = global::System.Data.CommandType.StoredProcedure;
            this._commandCollection[0].Parameters.Add(new global::System.Data.SqlClient.SqlParameter("@RETURN_VALUE", global::System.Data.SqlDbType.Int, 4, global::System.Data.ParameterDirection.ReturnValue, 10, 0, null, global::System.Data.DataRowVersion.Current, false, null, "", "", ""));
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Fill, true)]
        public virtual int Fill(ANGEL_TO_001_Ts_type_master.utfVCAR_TS_TYPE_MASTERDataTable dataTable) {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            if ((this.ClearBeforeFill == true)) {
                dataTable.Clear();
            }
            int returnValue = this.Adapter.Fill(dataTable);
            return returnValue;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        [global::System.ComponentModel.DataObjectMethodAttribute(global::System.ComponentModel.DataObjectMethodType.Select, true)]
        public virtual ANGEL_TO_001_Ts_type_master.utfVCAR_TS_TYPE_MASTERDataTable GetData() {
            this.Adapter.SelectCommand = this.CommandCollection[0];
            ANGEL_TO_001_Ts_type_master.utfVCAR_TS_TYPE_MASTERDataTable dataTable = new ANGEL_TO_001_Ts_type_master.utfVCAR_TS_TYPE_MASTERDataTable();
            this.Adapter.Fill(dataTable);
            return dataTable;
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(ANGEL_TO_001_Ts_type_master.utfVCAR_TS_TYPE_MASTERDataTable dataTable) {
            return this.Adapter.Update(dataTable);
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(ANGEL_TO_001_Ts_type_master dataSet) {
            return this.Adapter.Update(dataSet, "utfVCAR_TS_TYPE_MASTER");
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(global::System.Data.DataRow dataRow) {
            return this.Adapter.Update(new global::System.Data.DataRow[] {
                        dataRow});
        }
        
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.ComponentModel.Design.HelpKeywordAttribute("vs.data.TableAdapter")]
        public virtual int Update(global::System.Data.DataRow[] dataRows) {
            return this.Adapter.Update(dataRows);
        }
    }
}

#pragma warning restore 1591