
//----------------------------------------------------------------------------------------
// patterns & practices - Smart Client Software Factory - Guidance Package
//
// This file was generated by the "Add View" recipe.
//
// For more information see: 
// ms-help://MS.VSCC.v90/MS.VSIPCC.v90/ms.practices.scsf.2008apr/SCSF/html/02-09-010-ModelViewPresenter_MVP.htm
//
// Latest version of this Guidance Package: http://go.microsoft.com/fwlink/?LinkId=62182
//----------------------------------------------------------------------------------------

namespace Angel_to_003.Infrastructure.Module
{
    partial class TreeMainMenuView
    {
        /// <summary>
        /// The presenter used by this view.
        /// </summary>
        private Angel_to_003.Infrastructure.Module.TreeMainMenuViewPresenter _presenter = null;

        /// <summary> 
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        /// <summary> 
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                if (_presenter != null)
                    _presenter.Dispose();

                if (components != null)
                    components.Dispose();
            }

            base.Dispose(disposing);
        }

        #region Component Designer generated code

        /// <summary> 
        /// Required method for Designer support - do not modify 
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            System.Windows.Forms.TreeNode treeNode1 = new System.Windows.Forms.TreeNode("Заказ-наряд");
            System.Windows.Forms.TreeNode treeNode2 = new System.Windows.Forms.TreeNode("Общее состояние автомобилей");
            this.MainMenuTreeView = new System.Windows.Forms.TreeView();
            this.SuspendLayout();
            // 
            // MainMenuTreeView
            // 
            this.MainMenuTreeView.Dock = System.Windows.Forms.DockStyle.Fill;
            this.MainMenuTreeView.Location = new System.Drawing.Point(0, 0);
            this.MainMenuTreeView.Name = "MainMenuTreeView";
            treeNode1.Name = "WarehouseOrder";
            treeNode1.Text = "Заказ-наряд";
            treeNode2.Name = "CarCondition";
            treeNode2.Text = "Общее состояние автомобилей";
            this.MainMenuTreeView.Nodes.AddRange(new System.Windows.Forms.TreeNode[] {
            treeNode1,
            treeNode2});
            this.MainMenuTreeView.Size = new System.Drawing.Size(239, 357);
            this.MainMenuTreeView.TabIndex = 0;
            this.MainMenuTreeView.NodeMouseDoubleClick += new System.Windows.Forms.TreeNodeMouseClickEventHandler(this.MainMenuTreeView_NodeMouseDoubleClick);
            // 
            // TreeMainMenuView
            // 
            this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.Controls.Add(this.MainMenuTreeView);
            this.Name = "TreeMainMenuView";
            this.Size = new System.Drawing.Size(239, 357);
            this.ResumeLayout(false);

        }

        #endregion

        private System.Windows.Forms.TreeView MainMenuTreeView;
    }
}

